
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[CraftingMapper]

	[CraftingMapper.MysticalAgricultureReprocessorMapper]
		#Recipe mapper for Mystical Agriculture seed reprocessor recipes
		enabled = true

	[CraftingMapper.BotaniaElvenTradeMapper]
		#null
		enabled = true

	[CraftingMapper.DraconicEvolutionFusionMapper]
		#Recipe mapper for Draconic Evolution Fusion recipes
		enabled = true

	[CraftingMapper.Table]
		#Maps Extended Crafting Table recipes
		enabled = true

	[CraftingMapper.AppliedEnergisticsInscriberMapper]
		#Recipe mapper for Applied Energistics inscriber
		enabled = true

	[CraftingMapper.BloodMagicAlchemicalReactionChamberMapper]
		#null
		enabled = true

	[CraftingMapper.BotaniaRuneAlterMapper]
		#null
		enabled = true

	[CraftingMapper.EnderCrafter]
		#Maps extended crafting Ender Crafter recipes
		enabled = true

	[CraftingMapper.Compressor]
		#Maps the Extended Crafting compressor recipes
		enabled = true

	[CraftingMapper.MysticalAgricultureInfusionMapper]
		#Recipe mapper for Mystical Agriculture infusion recipes
		enabled = true

	[CraftingMapper.BotaniaTerraPlateMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicBloodAltarMapper]
		#null
		enabled = true

	[CraftingMapper.BotaniaPetalMapper]
		enabled = true

	[CraftingMapper.BotaniaPureDaisyMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicTartaricForgeMapper]
		#null
		enabled = true

	[CraftingMapper.Smithing]
		#Maps smithing recipes.
		enabled = true

	[CraftingMapper.Combination]
		#Maps Extended Crafting Combination recipes
		enabled = true

	[CraftingMapper.BloodMagicAlchemyArrayMapper]
		#null
		enabled = true

	[CraftingMapper.PsiTrickMapper]
		#Maps Psi trick crafting recipes
		enabled = true

	[CraftingMapper.AppliedEnergisticsGrinderMapper]
		#Recipe mapper for Applied Energistics grinder. NOTE: Optional outputs are ignored
		enabled = true

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe, SingleItemRecipe, or SmithingRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

	[CraftingMapper.BotaniaManaInfusionMapper]
		#null
		enabled = true

	[CraftingMapper.BloodMagicAlchemyTableMapper]
		#null
		enabled = true

	[CraftingMapper.MrCrayfishVehicleModFluidExtractorMapper]
		#ProjectE-Integration Recipe Mapper for Mr Crayfish Vehicle Mod Fluid Extractor Mapper. Required Mods: [vehicle]
		enabled = true

	[CraftingMapper.IndustrialForegoingDissolutionChamberMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Dissolution Chamber Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.IndustrialForegoingCrusherMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Crusher Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.IndustrialForegoingStoneWorksGenerateMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Stone Works Generate Mapper. Required Mods: [industrialforegoing] NOTE: Disabled by default.
		enabled = false

[ProjectEIntegrationRecipeMapper]

	[ProjectEIntegrationRecipeMapper.IceAndFireDragonForgeMapper]
		#Recipe mapper for Ice and Fire DragonForge recipes
		enabled = true

[enabledMappers]
	#Adds EMC Values to Chaos Awakens Items.
	ChaosAwakensMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = true
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Recipe mapper for custom recipes that don't implement IRecipe
	ProjectEIntegrationRecipeMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true

